server:
  port: 8802

spring:
  application:
    name: data-point
  datasource:
    url: jdbc:postgresql://localhost:5432/data_definition
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

developer:
  service:
    uri: http://localhost:8804/developers/